spring:
  application:
    name: ${parentArtifactId}
    sample-name: ${parentArtifactId}
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

logging:
  config: classpath:logback.xml